\input texinfo   @c -*-texinfo-*-
@set VERSION 1.36
@c %**start of header
@setfilename buttercup.info
@settitle Buttercup - Behaviour-Driven Emacs Lisp Testing
@c %**end of header
@copying
This file describes the Buttercup Emacs Lisp test framework.

Copyright @copyright{} 2024  Ola Nilsson

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license is included in the section entitled ``GNU
Free Documentation License''.

A copy of the license is also available from the Free Software
Foundation Web site at @url{https://www.gnu.org/licenses/fdl.html}.

@end quotation

The document was typeset with
@uref{https://www.gnu.org/software/texinfo/, GNU Texinfo}.

@end copying

@titlepage
@title Buttercup
@subtitle Behaviour-Driven Emacs Lisp Testing
@author Ola Nilsson
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of the contents at the beginning.
@contents

@ifnottex
@node Top
@top Buttercup

@insertcopying
@end ifnottex

@c Generate the nodes for this menu with `C-c C-u C-m'.
@menu
* Overview::
* Installation and basic use::
* Writing tests::
* Running tests::
* GNU Free Documentation License::
* Index::
@end menu

@c Update all node entries with `C-c C-u C-n'.
@c Insert new nodes with `C-c C-c n'.
@node Overview
@chapter Overview

@center @image{images/buttercup,,,Ranculus repens, photo by sannse,jpg}

Buttercup is a behavior-driven development framework for testing Emacs
Lisp code.  It allows to group related tests so they can share common
set-up and tear-down code, and allows the programmer to “spy” on
functions to ensure they are called with the right arguments during
testing.

The framework is heavily inspired by
@url{https://jasmine.github.io/edge/introduction.html,Jasmine}.

@c TODO: Use a
@heading Example
@c @node Example
@c @section Example

A simple test looks like this.  @strong{Please notice} that
@code{lexical-binding: t} is @emph{required} in files defining
buttercup tests.

@lisp
;;; lexical-binding is required -*- lexical-binding: t; -*-
(describe "A suite"
  (it "contains a spec with an expectation"
    (expect t :to-be t)))
@end lisp

@node Installation and basic use
@chapter Installation and basic use

Install buttercup from @url{https://elpa.nongnu.org,NonGNU ELPA}.  It
is also available in @url{https://stable.melpa.org,MELPA Stable} or in a
bleeding edge version from @url{https://melpa.org,MELPA}.  There is
usually no reason to use the bleeding edge version.  New stable
versions are released soon after major changes or bugfixes.

Tests are usually defined in Emacs Lisp files with a @samp{test-}
prefix, like @samp{test-feature.el}.  Test files are usually
structured as follows

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)
(describe "A suite"
  (it "contains a spec with an expectation"
    (expect t :to-be t))
  (it "contains another spec without an expectation"))
(describe "Another suite, without specs")
@end lisp 

Buttercup tests can be run in many ways, but a good way to start is
with the @command{buttercup} command included in the package.

@example
$ buttercup -L .
Running 1 out of 2 specs.

A suite
  contains a spec with an expectation (4.59ms)
  contains another spec without an expectation  PENDING (0.03ms)

Another suite, without specs

Ran 1 out of 2 specs, 0 failed, in 11.07ms.
@end example

@node Writing tests
@chapter Writing tests

Buttercup is a behavior-driven development framework for testing Emacs
Lisp code.  It does not depend on any other Emacs Lisp libraries.  It
has a clean, obvious syntax so that you can easily write tests.

It is heavily inspired by @url{https://jasmine.github.io/,Jasmine}.
So heavily inspired, in fact, that most of this page is more or less a
verbatim copy of the
@url{https://jasmine.github.io/edge/introduction.html,Jasmine
introduction}.

@c All code in this file can be run by Buttercup’s built-in markdown test
@c runner. Just use `make test` in the project directory to see the
@c output.

@menu
* Suites::
* Specs::
@end menu

@node Suites
@section Suites: ``describe'' your tests

A test suite begins with a call to the Buttercup macro @code{describe}
with the first parameter being a string describing the suite and the
rest being the body of code that implements the suite.

@strong{Please notice} that @code{lexical-binding: t} is
@emph{required} in files defining buttercup tests.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)
(describe "A suite"
  (it "contains a spec with an expectation"
    (expect t :to-be t)))
@end lisp

@node Specs
@section Specs

Specs are defined by calling the Buttercup macro @code{it}, which like
@code{describe} takes a string and code.  The string is the @var{title} of
the spec and the @var{code} is the spec, or test.  A spec contains one or
more @var{expectations} that test the state of the code.  An expectation in
Buttercup is an assertion that is either true or false.  A spec with
all true expectations is a passing spec.  A spec with one or more false
expectations is a failing spec.

@menu
* It's just functions::
* Expectations::
* Grouping Related Specs with @code{describe}::
* Disabling Suites::
* Pending Specs::
* Conditionally Skipping Specs::
* Spies::
* Warnings in tests::
@end menu

@node It's just functions
@subsection It's just functions

The code arguments to @code{describe} and @code{it} is just turned into
functions internally, so they can contain any executable code
necessary to implement the rules. Emacs Lisp scoping rules apply, so
make sure to define your spec file to be lexically scoped.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)
(describe "A suite is just a function"
  :var (a)
  (it "and so is a spec"
    (setq a t)
    (expect a :to-be t)))
@end lisp

@node Expectations
@subsection Expectations

Expectations are expressed with the @code{expect} macro.  Its first
argument is the actual value.  The second argument is a test keyword,
followed by expected values for the test to compare the actual value
against.

If there is no test, the argument is simply tested for being non-nil.
This can be used by people who dislike the matcher syntax or when
there is no suitable matcher.

@menu
* Matchers::
* Included matchers::
@end menu

@node Matchers
@subsubsection Matchers

Each matcher implements a boolean comparison between the actual value
and the expected value.  It is responsible for reporting to Buttercup
if the expectation is true or false.  Buttercup will then pass or fail
the spec.

Any matcher can evaluate to a negative assertion by prepending it with
the @code{:not} matcher.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)
(describe "The :to-be matcher compares with `eq'"
  (it "and has a positive case"
    (expect t :to-be t))
  (it "and can have a negative case"
    (expect nil :not :to-be t)))
@end lisp

@node Included matchers
@subsubsection Included matchers

Buttercup has a rich set of matchers included.  Each is used in the
example below --- all expectations and specs pass.  There is also the
ability to write custom matchers (see the
@code{buttercup-define-matcher} macro for further information) for
when a project’s domain calls for specific assertions that are not
included below.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)

(describe "Included matchers:"
  (it "The :to-be matcher compares with `eq'"
    (let* ((a 12)
           (b a))
      (expect a :to-be b)
      (expect a :not :to-be nil)))

  (describe "The :to-equal matcher"
    (it "works for simple literals and variables"
      (let ((a 12))
        (expect a :to-equal 12)))

    (it "should work for compound objects"
      (let ((foo '((a . 12) (b . 34)))
            (bar '((a . 12) (b . 34))))
        (expect foo :to-equal bar))))

  (it "The :to-have-same-items-as matcher compares two lists as sets"
    (let ((first (list "a" "b" "c"))
          (second (list "c" "a" "b"))
          (third (list "a" "c" "d"))
          (fourth (list "a" "b")))
      (expect first :to-have-same-items-as second)
      (expect second :to-have-same-items-as first)
      (expect first :not :to-have-same-items-as third)
      (expect third :not :to-have-same-items-as second)
      (expect first :not :to-have-same-items-as fourth)
      (expect fourth :not :to-have-same-items-as first)))

  (it "The :to-match matcher is for regular expressions"
    (let ((message "foo bar baz"))
      (expect message :to-match "bar")
      (expect message :to-match (rx "bar"))
      (expect message :not :to-match "quux")))

  (it "The :to-be-truthy matcher is for boolean casting testing"
    (let (a
          (foo "foo"))
      (expect foo :to-be-truthy)
      (expect a :not :to-be-truthy)))

  (it "The :to-contain matcher is for finding an item in a list"
    (let ((a '("foo" "bar" "baz")))
      (expect a :to-contain "bar")
      (expect a :not :to-contain "quux")))

  (it "The :to-be-less-than matcher is for mathematical comparisons"
    (let ((pi 3.1415926)
          (e 2.78))
      (expect e :to-be-less-than pi)
      (expect pi :not :to-be-less-than e)))

  (it "The :to-be-greater-than matcher is for mathematical comparisons"
    (let ((pi 3.1415926)
          (e 2.78))
      (expect pi :to-be-greater-than e)
      (expect e :not :to-be-greater-than pi)))

  (it "The :to-be-close-to matcher is for precision math comparison"
    (let ((pi 3.1415926)
          (e 2.78))
      (expect pi :not :to-be-close-to e 2)
      (expect pi :to-be-close-to e 0)))

  (describe "The :to-throw matcher"
    (it "is for testing if an expression throws an exception"
      (expect (+ 1 2) :not :to-throw)
      (expect (+ a 1) :to-throw))
    (it "accepts a symbol to check for the signal thrown"
      (expect (/ 1 0) :not :to-throw 'void-variable)
      (expect (+ a 1) :to-throw 'void-variable))
    (it "optionally matches arguments to signals"
        (expect (+ a 1) :not :to-throw 'void-variable '(b))
        (expect (+ a 1) :to-throw 'void-variable '(a)))
	(it "matches inherited signals"
	  (expect (signal 'overflow-error nil) :to-throw 'overflow-error)
	  (expect (signal 'overflow-error nil) :to-throw 'arith-error)
	  (expect (signal 'overflow-error nil) :to-throw 'error)
	  (expect (signal 'arith-error nil) :not :to-throw 'overflow-error)
	  (expect (signal 'arith-error nil) :to-throw 'arith-error)
	  (expect (signal 'arith-error nil) :to-throw 'error))))
@end lisp

If you are migrating from @samp{ERT}, you can also use @code{should}
and similar macros inside a buttercup test just like you would inside
an @code{ert-deftest} form.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'ert)
(require 'buttercup)

(describe "ERT support"
  (it "allows you to use ERT macros in tests"
    (let* ((a 12)
           (b a))
      (should (= a b))
      (should-not (eq a nil))
      (should-error (error "Throws an error")))))
@end lisp

@node Grouping Related Specs with @code{describe}
@subsection Grouping Related Specs with @code{describe}

The @code{describe} macro is for grouping related specs.  The string
parameter is for naming the collection of specs, and will be
concatenated with specs to make a spec’s full name.  This aids in
finding specs in a large suite.  If you name them well, your specs
read as full sentences in traditional
@url{http://en.wikipedia.org/wiki/Behavior-driven_development,@acronym{BDD}}
style.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)
(describe "A spec"
  (it "is just a function, so it can contain any code"
    (let ((foo 0))
      (setq foo (1+ foo))

      (expect foo :to-equal 1)))

  (it "can have more than one expectation"
    (let ((foo 0))
      (setq foo (1+ foo))

      (expect foo :to-equal 1)
      (expect t :to-equal t))))
@end lisp


@menu
* Declaring variables::
* Setup and Teardown::
* Nesting @code{describe} Blocks::
@end menu

@node Declaring variables
@subsubsection Declaring Variables

The @code{describe} macro supports the optional @code{:var} and
@code{:var*} args.  These bind variables for the suite by passing them
as a @samp{varlist} to the @code{let} and @code{let*} form
respectively.  Only one instance of @code{:var} or @code{:var*} is
allowed, and it must come first in the @code{describe} form.  It can
not be interspersed between @code{it} statements.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)
(describe "A spec using :VAR"
  :var ((foo 1))
  (it "has access to the variables bound in :VAR"
    (expect foo :to-be 1)))

(describe "A spec using :VAR*"
  :var* ((foo 1)
        (bar (1+ foo)))
  (it "has access to the variables bound in :VAR* which can refer \
to symbols already bound"
    (expect bar :to-be 2)))
@end lisp

@c It's important to note that @code{lexical-binding} must be
@c @samp{non-nil} for @code{:var} and @code{:var*} to work properly.
@c Within a test file this is usually set using a local file variable.

Using @code{:var} and @code{:var*} works just like the @code{let}
equivalents, but it's recommended to use the @code{:var} format to be
future proof.  Future internal changes in buttercup could break suites
using @code{let}.


@node Setup and Teardown
@subsubsection Setup and Teardown

To help a test suite
@url{https://en.wikipedia.org/wiki/Don%27t_repeat_yourself,@acronym{DRY}} up any
duplicated setup and teardown code, buttercup provides the
@code{before-each}, @code{after-each}, @code{before-all} and
@code{after-all} special forms.

As the name implies, code blocks defined with @code{before-each} are
called once before each spec in the @code{describe} is run, and the
@code{after-each} code blocks are called once after each spec.

Here is the same set of specs written a little differently. The
variable under test is defined at the top-level scope --- the
@code{describe} block --- and initialization code is moved into a
@code{before-each} block.  The @code{after-each} block resets the
variable before continuing.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)

(describe "A spec using `before-each' and `after-each'"
  :var (foo)
  (before-each
   (when (not foo)
     (setq foo 0))
   (setq foo (1+ foo)))

  (after-each
   (setq foo 0))

  (it "is just a function, so it can contain any code"
    (expect foo :to-equal 1))

  (it "can have more than one expectation"
    (expect foo :to-equal 1)
    (expect t :to-equal t)))
@end lisp

The @code{before-all} form is called only once before all the specs in
@code{describe} are run, and the @code{after-all} form is called after
all specs finish.  These functions can be used to speed up test suites
with expensive setup and teardown.

However, be careful using @code{before-all} and @code{after-all}!
Since they are not reset between specs, it is easy to accidentally
leak state between your specs so that they erroneously pass or fail.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)

(describe "A spec using `before-all' and `after-all'"
  :var (foo)
  (before-all
   (setq foo 1))

  (after-all
   (setq foo 0))

  (it "sets the initial value of foo before specs run"
    (expect foo :to-equal 1)
    (setq foo (1+ foo)))

  (it "does not reset foo between specs"
    (expect foo :to-equal 2)))
@end lisp

@node Nesting @code{describe} Blocks
@subsubsection Nesting @code{describe} Blocks

Calls to @code{describe} can be nested, with specs defined at any level.
This allows a suite to be composed as a tree of functions. Before a
spec is executed, buttercup walks down the tree executing each
@code{before-each} function in order. After the spec is executed, buttercup
walks through the @code{after-each} functions similarly.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)
(describe "A spec"
  :var (foo)
  (before-each
   (setq foo 0)
   (setq foo (1+ foo)))

  (after-each
   (setq foo 0))

  (it "is just a function, so it can contain any code"
    (expect foo :to-equal 1))

  (it "can have more than one expectation"
    (expect foo :to-equal 1)
    (expect t :to-equal t))

  (describe "nested inside a second describe"
    (let (bar)
      (before-each
       (setq bar 1))

      (it "can reference both scopes as needed"
        (expect foo :to-equal bar)))))
@end lisp

@node Disabling Suites
@subsection Disabling Suites

Suites and specs can be disabled by marking them as pending with the
@code{xdescribe} and @code{xit} macros, respectively.  Any suites or
specs inside a @code{xdescribe} suite is also pending.  Pending suites and
specs will be listed as pending in the results, but the containing
code will not be run.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)

(xdescribe "A spec"
  :var (foo)
  (before-each
    (setq foo 0)
    (setq foo (1+ foo)))

  (it "is just a function, so it can contain any code"
    (expect foo :to-equal 1)))
@end lisp

@node Pending Specs
@subsection Pending Specs

Pending specs do not run, but will be listed in the results.

Any spec declared with @code{xit} is marked as pending.

Any spec declared without a function body will also be marked as
pending in results.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)

(describe "Pending specs"
  (xit "can be declared using `xit'"
    (expect t :to-be nil))

  (it "can be declared with `it' but without a body"))
@end lisp


@node Conditionally Skipping Specs
@subsection Conditionally Skipping Specs

Use the @code{assume} macro to conditionally skip a spec.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)

(describe "Conditionally skip specs"
  (it "with the `assume' macro"
    (assume (fboundp 'new-function) "`new-function' not availeble")
    (expect (new-function))))
@end lisp

If the first argument to @code{assume} evals to @code{nil}, the spec
will be marked as pending, and the second arg @var{message} will be
added to the output.

@node Spies
@subsection Spies

Buttercup has test double functions called spies.  While other
frameworks call these mocks and similar, we call them spies, because
their main job is to spy in on function calls.  Also, Jasmine calls
them spies, and so do we.  A spy can stub any function --- whether it
already exists or not --- and tracks calls to it and all arguments.

Spies may only be created in @code{before-each} or @code{it} blocks.
Spies are removed and all counters reset after each spec and its
@code{after-each} blocks have completed.  There are special matchers
for interacting with spies.  The @code{:to-have-been-called} matcher
will return @samp{non-nil} if the spy was called at all.  The
@code{:to-have-been-called-with} matcher will return true if the
argument list matches any of the recorded calls to the spy.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)

(describe "A spy"
  :var (foo bar)
  (before-each
   (setf (symbol-function 'foo)
         (lambda (value)
           (setq bar value)))

   (spy-on 'foo)

   (foo 123)
   (foo 456 "another param"))

  (it "tracks that the spy was called"
    (expect 'foo :to-have-been-called)
    (foo 789))

  (it "resets tracking after each spec"
    (expect 'foo :not :to-have-been-called-with 789))

  (describe "that is defined in a nested `describe'"
    (before-each
      (spy-on 'foo :and-return-value 1))
    (it "will override any outer spy"
      (expect (foo 789) :to-equal 1)
      (expect 'foo :not :to-have-been-called-with 123)))

  (it "will not be active outside it's scope"
    (expect (foo 789) :to-equal nil))

  (it "tracks all arguments of its calls"
    (expect 'foo :to-have-been-called-with 123)
    (expect 'foo :to-have-been-called-with 456 "another param"))

  (it "stops all execution on a function"
    (expect bar :to-be nil)))
@end lisp

The @code{:to-have-been-called-times} matcher will return true if the
spy was called a certain number of times.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)

(describe "A spy"
  :var (foo bar)
  (before-each
   (setf (symbol-function 'foo)
         (lambda (value)
           (setq bar value)))

   (spy-on 'foo)

   (foo 123)
   (foo 456 "another param"))

  (it "tracks that the spy was called twice"
    (expect 'foo :to-have-been-called-times 2)))
@end lisp

@menu
* Spies and-call-through::
* and-return-value::
* and-call-fake::
* and-throw-error::
* Other tracking properties::
@end menu

@node Spies and-call-through
@subsubsection Spies: @code{:and-call-through}

The keyword argument @code{:and-call-through} to @code{spy-on} will
make the spy call the original function instead of returning
@code{nil}.

@lisp
;;; -*- lexical-binding: t; -*-
(require 'buttercup)

(describe "A spy, when configured to call through"
  :var (bar set-bar get-bar fetched-bar)
  (before-each
    (fset 'set-bar (lambda (val)
                     (setq bar val)))
    (fset 'get-bar (lambda ()
                     bar))

    (spy-on 'get-bar :and-call-through)

    (set-bar 123)
    (setq fetched-bar (get-bar)))

  (it "tracks that the spy was called"
    (expect 'get-bar :to-have-been-called))

  (it "should not affect other functions"
    (expect bar :to-equal 123))

  (it "when called returns the requested value"
    (expect fetched-bar :to-equal 123)))
@end lisp

@node and-return-value
@subsubsection Spies: @code{:and-return-value}

The keyword argument @code{:and-return-value} specifies the value the
spied-on function should return.

@lisp
;;; -*- lexical-binding: t; -*-
(describe "A spy, when configured to fake a return value"
  :var (bar set-bar get-bar fetched-bar)
  (before-each
    (fset 'set-bar (lambda (val)
                     (setq bar val)))
    (fset 'get-bar (lambda ()
                     bar))

    (spy-on 'get-bar :and-return-value 745)

    (set-bar 123)
    (setq fetched-bar (get-bar)))

  (it "tracks that the spy was called"
    (expect 'get-bar :to-have-been-called))

  (it "should not affect other functions"
    (expect bar :to-equal 123))

  (it "when called returns the requested value"
    (expect fetched-bar :to-equal 745)))
@end lisp


@node and-call-fake
@subsubsection Spies: @code{:and-call-fake}

The keyword argument @code{:and-call-fake} delegates calls to a
supplied function.

@lisp
;;; -*- lexical-binding: t; -*-
(describe "A spy, when configured with an alternate implementation"
  :var (bar set-bar get-bar fetched-bar)
  (before-each
    (fset 'set-bar (lambda (val)
                     (setq bar val)))
    (fset 'get-bar (lambda ()
                     bar))

    (spy-on 'get-bar :and-call-fake (lambda () 1001))

    (set-bar 123)
    (setq fetched-bar (get-bar)))

  (it "tracks that the spy was called"
    (expect 'get-bar :to-have-been-called))

  (it "should not affect other functions"
    (expect bar :to-equal 123))

  (it "when called returns the requested value"
    (expect fetched-bar :to-equal 1001)))
@end lisp

@node and-throw-error
@subsubsection Spies: @code{:and-throw-error}

With the keyword argument @code{:and-throw-error}, all calls to the
spy will @code{signal} the specified value as an error.

@lisp
;;; -*- lexical-binding: t; -*-
(describe "A spy, when configured to throw an error"
  :var (bar set-bar get-bar fetched-bar)
  (before-each
    (fset 'set-bar (lambda (val)
                     (setq bar val)))
    (fset 'get-bar (lambda ()
                     bar))

    (spy-on 'get-bar :and-throw-error 'error))

  (it "throws the error"
    (expect (get-bar)
            :to-throw 'error)))
@end lisp

@node Other tracking properties
@subsubsection Other tracking properties

Every call to a spy is tracked and exposed using the @code{spy-calls}
accessor. This tracks both successful calls and calls that throw
errors.

@code{spy-calls-any} returns @code{nil} if the spy has not been called
at all, and then @code{t} once at least one call happens.
@code{spy-calls-count} returns the number of times the spy was called.
@code{spy-calls-args-for} returns the arguments passed to a given call
(by index).  @code{spy-calls-all-args} returns the arguments to all
calls.  @code{spy-calls-all} returns the context (current buffer,
arguments passed and return status) of all calls.
@code{spy-calls-most-recent} returns the context of the most recent
call.  @code{spy-calls-first} returns the context for the first call.

Contexts are represented by instances of the @code{spy-context} struct with
the slots @code{args}, @code{current-buffer}, @code{return-value} and
@code{thrown-signal}.  The @code{return-value} and @code{thrown-signal} slots
represent the return status.  Calling @code{spy-context-return-value} for a
context representing a raised signal (or vice versa) will raise an
error.  Test the context type with @code{spy-context-return-p} and
@code{spy-context-thrown-p}.

Finally, @code{spy-calls-reset} clears all tracking for a spy.

@lisp
;;; -*- lexical-binding: t; -*-
(describe "A spy"
  :var (set-foo foo)
  (before-each
    (fset 'set-foo (lambda (val &rest ignored)
                     (setq foo val)))
    (spy-on 'set-foo))

  (it "tracks if it was called at all"
    (expect (spy-calls-any 'set-foo)
            :to-equal
            nil)

    (set-foo 5)

    (expect (spy-calls-any 'set-foo)
            :to-equal
            t))

  (it "tracks the number of times it was called"
    (expect (spy-calls-count 'set-foo)
            :to-equal
            0)

    (set-foo 2)
    (set-foo 3)

    (expect (spy-calls-count 'set-foo)
            :to-equal
            2))

  (it "tracks the arguments of each call"
    (set-foo 123)
    (set-foo 456 "baz")

    (expect (spy-calls-args-for 'set-foo 0)
            :to-equal
            '(123))

    (expect (spy-calls-args-for 'set-foo 1)
            :to-equal
            '(456 "baz")))

  (it "tracks the arguments of all calls"
    (set-foo 123)
    (set-foo 456 "baz")

    (expect (spy-calls-all-args 'set-foo)
            :to-equal
            '((123)
              (456 "baz"))))

  (it "can provide the context and arguments to all calls"
    (set-foo 123)

    (expect (spy-calls-all 'set-foo)
            :to-equal
            `(,(make-spy-context :current-buffer (current-buffer)
                                 :args '(123)))))

  (it "has a shortcut to the most recent call"
    (set-foo 123)
    (set-foo 456 "baz")

    (expect (spy-calls-most-recent 'set-foo)
            :to-equal
            (make-spy-context :current-buffer (current-buffer)
                              :args '(456 "baz"))))

  (it "has a shortcut to the first call"
    (set-foo 123)
    (set-foo 456 "baz")

    (expect (spy-calls-first 'set-foo)
            :to-equal
            (make-spy-context :current-buffer (current-buffer)
                              :args '(123))))

  (it "tracks the return values and error signals of each call"
    ;; Set up `set-foo' so that it can either return a value or throw
    ;; an error
    (spy-on 'set-foo :and-call-fake
            (lambda (val &rest ignored)
              (if (>= val 0)
                  val
                (error "Value must not be negative"))))
    (expect (set-foo 1) :to-be 1)
    (expect (set-foo -1) :to-throw 'error)
    (expect (spy-context-return-p (spy-calls-first 'set-foo)))
    (expect
     (spy-context-return-value (spy-calls-first 'set-foo))
     :to-be 1)
    ;; Trying to get the thrown signal from a call that didn't throw a
    ;; signal is an error
    (expect
     (spy-context-thrown-signal
      (spy-calls-first 'set-foo))
     :to-throw)

    (expect (spy-context-thrown-p (spy-calls-most-recent 'set-foo)))
    (expect
     (spy-context-thrown-signal
      (spy-calls-most-recent 'set-foo))
     :to-equal '(error "Value must not be negative"))
    ;; Trying to get the return value from a call that threw a signal
    ;; raises an error
    (expect
     (spy-context-return-value
      (spy-calls-most-recent 'set-foo))
     :to-throw)
    ;; Use :return-value and :thrown-signal
    ;; to create matching spy-contexts
    (expect
     (spy-calls-all 'set-foo)
      :to-equal
      (list
       (make-spy-context :args '(1)
                         :current-buffer (current-buffer)
                         :return-value 1)
       (make-spy-context
         :args '(-1)
         :current-buffer (current-buffer)
         :thrown-signal '(error "Value must not be negative")))))

  (it "counts the number of successful and failed calls"
    ;; Set up `set-foo' so that it can either return a value or throw
    ;; an error
    (spy-on 'set-foo :and-call-fake
            (lambda (val &rest ignored)
              (if (>= val 0)
                  val
                (error "Value must not be negative"))))
    (expect (set-foo 1) :to-be 1)
    (expect (set-foo 2) :to-be 2)
    (expect (set-foo 3) :to-be 3)
    (expect (set-foo -1) :to-throw 'error)
    (expect (set-foo -2) :to-throw 'error)
    (expect (set-foo -3) :to-throw 'error)
    (expect (set-foo -4) :to-throw 'error)

    (expect (spy-calls-count 'set-foo)
            :to-be 7)
    (expect (spy-calls-count-returned 'set-foo)
            :to-be 3)
    (expect (spy-calls-count-errors 'set-foo)
            :to-be 4))

  (it "can be reset"
    (set-foo 123)
    (set-foo 456 "baz")

    (expect (spy-calls-any 'set-foo)
            :to-be
            t)

    (spy-calls-reset 'set-foo)

    (expect (spy-calls-any 'set-foo)
            :to-be
            nil)))
@end lisp

@node Warnings in tests
@subsection Warnings in tests

By default, buttercup captures any warning emitted during a test and
displays them all after the test completes in order to keep the output
readable.  If you need to suppress this (for example if your test
deals with the warnings itself), you can use the macro
@code{buttercup-suppress-warning-capture}, which works like
@code{progn} but suppresses buttercup's warning capturing within the
body.

@lisp
;;; -*- lexical-binding: t; -*-
(describe "A test"
  (it "can issue warnings while running"
    (display-warning
      'buttercup
      "This warning should be visible after the test report.")
    (expect (+ 2 2) :to-equal 4))

  (it "can capture its own warnings as part of the test"
    (buttercup-suppress-warning-capture
      (let ((warning-text
             (format
               "This warning, issued at %s should be sent to the *Warnings* buffer as normal."
               (current-time-string))))
        (display-warning 'buttercup warning-text)
        (expect (with-current-buffer "*Warnings*"
                  (buffer-string))
                :to-match (regexp-quote warning-text))))))
@end lisp


@node Running tests
@chapter Running tests

@menu
* Usage::
@end menu

@node Usage
@section Usage

Buttercup is primarily meant to be used non-interactively, to
automatically test a project independent of a user’s setup, before a
commit and on a continuous integration platform.  Because of this, the
recommended workflow for buttercup does not use interactive commands
but instead the command line.

@menu
* Cask::
* Eldev::
* Eask::
* Projectile::
* Travis::
@end menu

@node Cask
@subsection Cask

@url{https://github.com/cask/cask,Cask} is a project to create an
environment separate from your usual interactive Emacs environment.
This allows you to install the packages your project depends on, and
only those, and test your project in a well-defined environment.

Buttercup works best in such environments, so the following best
practices rely on Cask to be installed.

@menu
* Cask directory layout::
* Running tests with Cask::
@end menu

@node Cask directory layout
@subsubsection Cask directory layout

A basic project layout requires a project file, called @file{feature.el}
here, a @file{Cask} file to define dependencies, and a @file{tests/} directory
for tests.  It should look roughly like this:

@example
feature/feature.el
        Cask
        tests/test-feature.el
@end example

@subsubheading @file{feature.el}

@lisp
(defun featurize (bug feature)
  (format "It's not a %s, it's a %s" bug feature))

(provide 'feature)
@end lisp

@subsubheading @file{Cask}

@lisp
(source gnu)
(source melpa-stable)

(development
 (depends-on "buttercup"))
@end lisp

@subsubheading @file{tests/test-feature.el}

@lisp
;;; -*- lexical-binding: t; -*-
(require 'feature)

(describe "The feature"
  (it "can use bug and feature"
    (expect (featurize "bug" "feature")
            :to-equal
            "It's not a bug, it's a feature")))
@end lisp

@node Running tests with Cask
@subsubsection Running tests with Cask

You can now use Cask to run your tests.

First, you have to install the dependencies. You only have to do this
once, or when the dependencies change:

@example
$ @command{cask}
Extracting buttercup-1.1/
Extracting buttercup-1.1/buttercup-compat.el
Extracting buttercup-1.1/buttercup.el
Extracting buttercup-1.1/bin/
Extracting buttercup-1.1/bin/buttercup
Extracting buttercup-1.1/buttercup-pkg.el
Generating autoloads for buttercup-compat.el...
Generating autoloads for buttercup-compat.el...done
Generating autoloads for buttercup-pkg.el...
Generating autoloads for buttercup-pkg.el...done
Generating autoloads for buttercup.el...
Generating autoloads for buttercup.el...done
@end example

Now, you can run your tests:

@example
$ @command{cask} exec buttercup -L .
Running 1 specs.

The feature
  can use bug and feature

Ran 1 specs, 0 failed, in 0.0 seconds.
@end example

That’s it. Buttercup’s built-in discover test runner looks for files
named @file{test-*.el}, @file{*-test.el} or @file{*-tests.el}.

Use the @option{--pattern} @var{PATTERN} option to only run tests with
names matching @var{PATTERN}.  The @option{--pattern} option can be
used multiple times, in which case tests will be run if they match any
of the given patterns.  Combine with the @option{--no-skip} option to
filter out the skipped tests.

You can run this command whichever way you like.  Common choices
include a makefile or shell scripts.

@node Eldev
@subsection Eldev

@url{https://github.com/doublep/eldev,Eldev} is another Elisp build tool
and has built-in support for Buttercup.  Like Cask, it installs
dependencies of your project automatically, ensuring consistent
environment.

@menu
* Eldev directory layout::
* Running tests with Eldev::
@end menu

@node Eldev directory layout
@subsubsection Eldev directory layout

Typical project layout used for Cask also works for Eldev.  However,
the tool is very liberal and with a couple of lines you can configure
it to handle almost any layout a project could have (see the
@url{https://github.com/doublep/eldev#testing,Eldev documentation} if
needed).

Unlike Cask, however, Eldev needs that your test files include form
@code{(require 'buttercup)}.  Otherwise you will get Elisp errors like
@samp{“Symbol’s function definition is void: describe”}.  Basically, Eldev
requires that the @file{.el} files are @emph{self-contained} and do not depend
on certain external tool.

@node Running tests with Eldev
@subsubsection Running tests with Eldev

The tool installs project dependencies automatically when needed, so
you don’t have to bother about that.  All you need to do is to ensure
the main file of the project correctly declares them.

You also don’t need to declare that the project uses Buttercup for
testing: Eldev will determine that on-the-fly.

To run your test, just execute:

@example
$ @command{eldev} test
[1/1] Installing package ‘buttercup’ (1.23) from ‘melpa-stable’...
Running 1 specs.

The feature
  can use bug and feature (2.58ms)

Ran 1 specs, 0 failed, in 2.68ms.
@end example

You can also specify patterns on the command line, to avoid running
all the tests at once, i.e.:

@example
$ @command{eldev} test foo
@end example

If you have several test files, you can avoid running all the tests by
specifying filename after @option{-f} (@option{--file}) option:

@example
$ @command{eldev} test @option{-f} @file{main.el}
@end example

For more information, please see tool’s own documentation, especially
the section about
@url{https://github.com/doublep/eldev#testing,testing}.

@node Eask
@subsection Eask
Eask is very similar to Cask (@pxref{Cask}); anything that applies to Cask will apply to Eask

@url{https://github.com/emacs-eask/cli,Eask} is an actively maintained
replacement for Cask.

@menu
* Eask directory layout::
* Running tests with Eask::
@end menu

@node Eask directory layout
@subsubsection Eask project directory layout

The project directory layout is similar to Cask (@pxref{Cask directory
layout}). But instead of @file{Cask}-file, you should have @file{Eask}-file as
a replacement.

A basic project layout requires a project file, called @file{feature.el}
here, an @file{Eask}-file to define dependencies, and a @file{tests/} directory
for tests. It should look roughly like this:

@example
feature/feature.el
        Eask
        tests/test-feature.el
@end example

@subsubheading @file{feature.el}

@lisp
(defun featurize (bug feature)
  (format "It's not a %s, it's a %s" bug feature))

(provide 'feature)
@end lisp

@subsubheading @file{Eask}

@lisp
(source 'gnu)
(source 'melpa-stable)

(development
 (depends-on "buttercup"))
@end lisp

@subsubheading @file{tests/test-feature.el}

@lisp
;;; -*- lexical-binding: t; -*-
(require 'feature)

(describe "The feature"
  (it "can use bug and feature"
    (expect (featurize "bug" "feature")
            :to-equal
            "It's not a bug, it's a feature")))
@end lisp

@node Running tests with Eask
@subsubsection Running tests with Eask

You can now use Eask to run your tests.

First, you have to install the dependencies. You only have to do this once, or
when the dependencies change:

@example
$ @command{eask} install-deps @option{--dev}

Installing 1 development dependency...
Loading package information... done
  - Installing buttercup (20230119.2337)... done
(Total of 1 dependency installed, 0 skipped)
@end example

Now, you can run your tests:

@example
$ @command{eask} exec buttercup @option{-L} .
...

Running 1 specs.

The feature
  can use bug and feature

Ran 1 specs, 0 failed, in 0.0 seconds.
@end example

That’s it.  Buttercup’s built-in discover test runner looks for files
named @file{test-*.el}, @file{*-test.el} or @file{*-tests.el}.

Use the @option{--pattern} @var{PATTERN} option to only run tests with
names matching @var{PATTERN}.  The @option{--pattern} option can be
used multiple times, in which case tests will be run if they match any
of the given patterns. Combine with the @option{--no-skip} option to
filter out the skipped tests.

You can run this command whichever way you like. Common choices
include a Makefile or shell scripts.

See the @url{https://emacs-eask.github.io/,Eask documentation} on
Eask's own page for more information.

@node Projectile
@subsection Projectile

If you use @url{https://github.com/bbatsov/projectile,Projectile} for
interacting with your projects you can set the "default" project test
command to be available when you invoke @code{projectile-test-project}.
Create a @file{.dir-locals.el} file in the the root of your project tree
(next to your @file{Cask} file).  An example:

@subsubheading @file{.dir-locals.el}

@lisp
((nil . ((eval . (progn
                   (require 'projectile)
                   (puthash (projectile-project-root)
                            "cask exec buttercup -L ."
                            projectile-test-cmd-map))))))
@end lisp

If you are using Eldev as build tool, Projectile should provide
testing command on its own, so you don’t need any special steps.

@node Travis
@subsection Travis

@menu
* Cask on Travis::
* Eldev on Travis::
* Eask on Travis::
@end menu

@node Cask on Travis
@subsubsection Cask on Travis

If your project is hosted on github, you can use
@url{https://travis-ci.org/,Travis CI} as your continuous integration
environment.  Buttercup can easily be used in such a setup.  Simply add
the following @file{.travis.yml} file:

@example
language: emacs-lisp
sudo: false
cache: apt
env:
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
before_install: |
  curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw \
    >travis.sh &&
    source ./travis.sh
  evm install $EVM_EMACS --use --skip
  cask
install:
  - cask install
script:
  - emacs --version
  - cask exec buttercup -L .
@end example

Most of the complexity here is from installing
@url{https://github.com/rejeep/evm,EVM} and Cask to be able to test
your project using different Emacs versions.

@node Eldev on Travis
@subsubsection Eldev on Travis

For Eldev, use the following @file{.travis.yml} file:

@example
language: emacs-lisp
dist: trusty

env:
  # Add more lines like this if you want to test
  # on different Emacs versions.
  - EVM_EMACS=emacs-26.3-travis

install: |
  curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/travis-eldev-and-evm \
    >x.sh &&
    source ./x.sh
  evm install $EVM_EMACS --use

script:
  - eldev -p -dtT test
@end example

For details, see the
@url{https://github.com/doublep/eldev#continuous-integration,Eldev CI documentation}.

@node Eask on Travis
@subsubsection Eask on Travis

For Eask, please see the
@url{https://emacs-eask.github.io/Continuous-Integration/Travis-CI/,
Eask Travis documentation}


@comment APPENDICES START HERE

@node GNU Free Documentation License
@appendix GNU Free Documentation License
@c Get fdl.texi from https://www.gnu.org/licenses/fdl.html
@include fdl-1.3.texi

@node Index
@unnumbered Index

@printindex cp

@bye
